//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuWaOh.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<elements>\r\n\t<element imgPath=\"assets/elements/nature.png\">Nature</element>\r\n\t<el" +
            "ement imgPath=\"assets/elements/participation.png\">Participation</element>\r\n</ele" +
            "ments>")]
        public string elements {
            get {
                return ((string)(this["elements"]));
            }
            set {
                this["elements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<cardtypes>
	<cardtype imgPath=""assets/cardtypes/normal.png"">Normal</cardtype>
	<cardtype imgPath=""assets/cardtypes/effect.png"">Effect</cardtype>
<cardtype imgPath=""assets/cardtypes/spell.png"">Spell</cardtype>
<cardtype imgPath=""assets/cardtypes/trap.png"">Trap</cardtype>
</cardtypes>")]
        public string cardtypes {
            get {
                return ((string)(this["cardtypes"]));
            }
            set {
                this["cardtypes"] = value;
            }
        }
    }
}
